server:
  port: 4001

#spring:
#  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:63343"
#            allowedHeaders: "*"
#            allowedMethods:
#              - POST